---
- name: "Get Kernel version"
  command: uname -r
  register: kernel_version

- name: "Set os image property"
  set_fact:
      os_version: "{{ ansible_distribution }}-{{ ansible_distribution_version }}"
      kernel_version: "{{ kernel_version.stdout }}"

- name: "Create facts directory ({{ playbook_dir }}/.facts)"
  local_action:
    module: file
    path: "{{ playbook_dir }}/.facts"
    state: directory
  become: False

- name: Save facts
  local_action:
    module: copy
    content: "{{ vars[item] }}"
    dest: "{{ playbook_dir }}/.facts/{{ item }}"
  become: False
  with_items: "{{ facts }}"
